from summarus.readers.summarization_reader import SummarizationReader
from summarus.readers.cnn_dailymail_reader import CNNDailyMailReader
from summarus.readers.contracts_reader import ContractsReader
from summarus.readers.lenta_reader import LentaReader
from summarus.readers.ria_reader import RIAReader
